export const API_BASE_URL = "https://mywebnotes.me:5000"
export const NOTES_ENDPOINT = "/api/notes/all";
export const NOTES_SHARE_ENDPOINT = "/api/notes/shared";
export const NOTES_SHARE_ID_ENDPOINT = "/api/notes/share/";
export const NOTES_ID_ENDPOINT = "/api/notes/";
export const AUTH_ENDPOINT = "/api/auth";
export const AUTH_LOGIN_ENDPOINT = "/api/auth/login";
export const AUTH_REGISTER_ENDPOINT = "/api/auth/register";
export const AUTH_REGISTER_GET = "/api/auth/register?username="
export const AUTH_LOGOUT_ENDPOINT = "/api/auth/logout";
export const AUTH_REFRESH_ENDPOINT = "/api/auth/refresh";
export const LOCAL_STORAGE_WIDTH_KEY = "WIDTH";