version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/instance
      - ./server/migrations:/app/server/migrations
    environment:
      - FLASK_APP=./server/app.py
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./server/env.list

volumes: 
  db_data: