version: '3.9'

services:
  client:
    build: ./client
    image: cookiechomper/client:latest
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app_network
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: cookiechomper/server:latest
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/instance
      - ./server/migrations:/app/server/migrations
    environment:
      - FLASK_APP=./server/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/instance/db.db
      - SQLALCHEMY_TRACK_MODIFICATIONS=false
    env_file:


      - ./server/env.list

    command: /bin/bash -c "python -m flask db upgrade &&  python -m gunicorn --chdir=./server --bind 0.0.0.0:5000 --workers 4 --threads 2 --timeout 0 app:app"
    networks:
      - app_network
volumes: 
  db_data:

networks:
  app_network: