"""empty message

Revision ID: 69020b5bcf53
Revises: 3638ab3ed7f7
Create Date: 2023-03-23 14:36:22.355752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69020b5bcf53'
down_revision = '3638ab3ed7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
            batch_op.alter_column('id', type_=sa.String(length=36)) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
